name: pointcloud-platform-backend
services:
  pocketbase:
    build: .
    ports:
      - 8090:8090
    volumes:
      - ./pb_data:/pb/pb_data
      - ./pb_hooks:/pb/pb_hooks
      - ./pb_migrations:/pb/pb_migrations
